name: lint

on:
  push:
    branches:
      - main
  pull_request:

env:
  GLEAM_VERSION: '1.10.0'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.0"
          gleam-version: ${{ env.GLEAM_VERSION }}
          rebar3-version: "3"
      - run: gleam format --check src
